#!/bin/bash
#SBATCH --job-name=prediction
#SBATCH -c 1
#SBATCH --time=72:00:00
#SBATCH --output=/home/ikvasilev/logs/prediction_multiple_ts_1_%j.log
source /home/ikvasilev/my_env/bin/activate
python ./main.py $1
