#!/bin/bash
#SBATCH --job-name=prediction
#SBATCH -c 4
#SBATCH --time=72:00:00
#SBATCH --output=/home/ikvasilev/prediction_multiple_ts_1.log
source /home/ikvasilev/my_env/bin/activate
epsilon=$1
python ./main.py $epsilon
