#!/bin/bash

# Параметры
start=0
end=60000
steps=64
mkdir -p "home/ikvasilev/save"

experiment_name="size_experiment"

if [ -f "/home/ikvasilev/PaTHoP/results/$experiment_name" ]; then
    # Перемещаем файл
    mv --backup=simple "/home/ikvasilev/PaTHoP/results/$experiment_name" "home/ikvasilev/save/"
    echo "Файл успешно перемещён в home/ikvasilev/save/"
else
    echo "файл не создан"
fi


# Вычисляем шаг
step=$(( (end - start) / (steps - 1) ))

for (( i=0; i<steps; i++ )); do
    size=$(( start + i * step ))
    echo "Submitting job with size=$size"
    sbatch -A proj_1685 ./bash 0.01 10 $size $experiment_name
done


for (( i=0; i<steps; i++ )); do
    size=$(( start + i * step ))
    echo "Submitting job with size=$size"
    sbatch -A proj_1685 ./bash 0.1 10 $size $experiment_name
done


for (( i=0; i<steps; i++ )); do
    size=$(( start + i * step ))
    echo "Submitting job with size=$size"
    sbatch -A proj_1685 ./bash 1 10 $size $experiment_name
done