#!/bin/bash
#SBATCH --job-name=optuna_trial_%j
#SBATCH --output=/home/ikvasilev/logs/slurm_out%j.log
#SBATCH --time=00:45:00
#SBATCH --cpus-per-task=1
source /home/ikvasilev/my_env/bin/activate
python valid_main.py "$@"
