#!/bin/bash
#SBATCH --job-name=prediction
#SBATCH -c 12
#SBATCH --time=72:00:00
#SBATCH --output=/home/ikvasilev/PaTHoP/assets/logs/prediction_multiple_ts_%j.log
source ~/.bashrc
conda activate myenv

python ./submain.py $1 $2 $3 $4 $5 $6